# ------------------- THEME -------------------

theme: jekyll-theme-chirpy
lang: en

# ------------------- BASIC INFO -------------------

title: "Debugging My Dreams"
tagline: "A Computer Engineering Journey by Maryam"

description: >
  A personal blog documenting my Computer Engineering journey,
  challenges, and learning experiences.

url: "https://maryamabdulbasit309.github.io"
baseurl: "/Maryam-basit"

timezone: Asia/Karachi

# ------------------- PROFILE -------------------

avatar: "/assets/img/m.jpg"

author:
  name: "Maryam Abdul Basit"
  bio: "Computer Engineering student sharing my journey and learning experiences."

social:
  name: "Maryam Abdul Basit"
  links:
    - "https://github.com/maryamabdulbasit309"

github:
  username: "maryamabdulbasit309"

# ------------------- DESIGN -------------------

theme_mode: dark

# ------------------- FEATURES -------------------

toc: true
paginate: 10

# ------------------- ANALYTICS -------------------

analytics:
  google:
    id:

# ------------------- COMMENTS -------------------

comments:
  provider:

# ------------------- PWA -------------------

pwa:
  enabled: true
  cache:
    enabled: true

# ------------------- COLLECTIONS -------------------

collections:
  tabs:
    output: true
    sort_by: order

# ------------------- DEFAULTS -------------------

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# ------------------- SASS -------------------

sass:
  style: compressed

# ------------------- EXCLUDE -------------------

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
